dist: bionic
language: go
go:
  - 1.13.x

services:
  - docker

install: true

script:
  - env GO111MODULE=on make ci-test stop-docker-test install

after_success:
  - bash <(curl -s https://codecov.io/bash)
